
[database]
uri = "neo4j+s://14394066.databases.neo4j.io"
user = "neo4j" 
password = 'cl4ouH3LzGzpP8tbIfdR8SPcAHwfos0AV8YzHrJN1Qs'
sample = 'test_data/R139_signup.xlsx'


[api]
api_key = "d4954786fb0f4a3e8a85fe828fc079bf"

[model]
model_path = "Model/central_model_rf.pkl"
